version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: ambassador
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 33066:3306
