export enum ProfileTypes {
  GET_ALL_USERS = "@@users/GET_PROFILE",
  GET_ALL_USERS_SUCCESSFUL = "@@users/GET_PROFILE_SUCCESSFUL",
  GET_ALL_USERS_FAILED = "@@users/GET_PROFILE_FAILED",

  GET_USER_INFO = "@@users/GET_USER_INFO",
  GET_USER_INFO_SUCCESSFUL = "@@users/GET_USER_INFO_SUCCESSFUL",
  GET_USER_INFO_FAILED = "@@users/GET_USER_INFO_FAILED",
}
